config/routes.rb
NewApp::Application.routes.draw do
  root to: "staticpages#home"
  get "signup", to: "users#new"
 
  get "staticpages/about"
  get "staticpages/signup"
  get "staticpages/signin"
  get "staticpages/contact"
 
  
  
  get "staticpages/help"
  get "staticpages/home"
  get "home" , to: "staticpages#home"
  get "help" , to: "staticpages#help"
  
  resources :users

end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id         :integer          not null, primary key
#  name       :string(255)
#  email      :string(255)
#  created_at :datetime
#  updated_at :datetime
#

class User < ActiveRecord::Base
  attr_accessible :name, :email, :password , :password_confirmation
  has_secure_password

  before_save  { |user| user.email = email.downcase }

  validates :name, presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, 
	     format: { with: VALID_EMAIL_REGEX},
	     uniqueness: { case_sensitive: false }
  validates :password, presence: true, length: { minimum: 6}
  validates :password_confirmation, presence: true	 
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/staticpages_controller.rb
class StaticpagesController < ApplicationController
  def about
  end

  def signup
  end

  def signin
  end

  def contact
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
     @user=User.find(params[:id])	
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render action: 'show', status: :created, location: @user }
      else
        format.html { render action: 'new' }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:name, :email)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper

def full_title(page_title)
	base_title = "Ruby on Rails Tutorial Sample App"
	if page_title.empty?
		base_title
	else
		"#{base_title} | #{page_title}"
		end
	end

end

app/helpers/staticpages_helper.rb
module StaticpagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_footer.html.erb
<footer class="footer">
	<small>
		<a href="http://railstutorial.org/">Rails Tutorial</a>
	</small>
	<nav>
		<ul>
			<li><%= link_to "About", '#' %></li>
			<li><%= link_to "Contact", '#' %></li>
			<li><a href="http://news.railstutorial.org/">News</a></li>
		</ul>
	</nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top">
     <div class="navbar-inner">
       <div class="container">
        <%= link_to "sample app",'#',id: "logo" %>
         <nav>
           <ul class="nav pull-right">
               <li><%= link_to "Home", home_path %></li>    
		<li><%= link_to "Help", help_path %></li> 
		<li><%= link_to "Sign in", signup_path %></li>
	   </ul>
	</nav>
	</div>
	</div>
	</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= full_title(yield(:title)) %></title>
  <%= stylesheet_link_tag    "application", media: "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
     <%= render 'layouts/header' %>
     <div class="container">
	<%= yield %>
	<%= render 'layouts/footer' %>
	<%= debug(params) if Rails.env.development? %>
	</div>
</body>
</html>

app/views/staticpages/About.html.erb
<h1>Staticpages#About</h1>
<p>Find me in app/views/staticpages/About.html.erb</p>

app/views/staticpages/about.html.erb
<h1>Staticpages#about</h1>
<p>Find me in app/views/staticpages/about.html.erb</p>

app/views/staticpages/contact.html.erb
<h1>Staticpages#contact</h1>
<p>Find me in app/views/staticpages/contact.html.erb</p>

app/views/staticpages/help.html.erb
<h1>Help</h1>
<p>
	Get help on the Ruby on Rails Tutorial at the
	<a href="http://railstutorial.org/help">Rails Tutorial help page</a>.
	To get help on this sample app, see the
	<a href="http://railstutorial.org/book">Rails Tutorial book</a>.
</p>

app/views/staticpages/home.html.erb
<dic class="center hero-unit">
<h1>Welcome to the sample App</h1>
   <h2> This is the home page for the
	  <a href="http://railstutorial.org/">Ruby on Rails Tutorial</a>
	  sample application.
   <h2>
	<%= link_to "Sign up now!",signup_path,class: "btn btn-large btn-primary" %>
</div>

<%= link_to image_tag("rails.png",alt: "Rails"), 'http://rubyonrails.org.' %>

app/views/staticpages/sign in.html.erb
<h1>Staticpages#sign in</h1>
<p>Find me in app/views/staticpages/sign in.html.erb</p>

app/views/staticpages/sign up.html.erb
<h1>Staticpages#sign up</h1>
<p>Find me in app/views/staticpages/sign up.html.erb</p>

app/views/staticpages/signin.html.erb
<h1>Staticpages#signin</h1>
<p>Find me in app/views/staticpages/signin.html.erb</p>

app/views/staticpages/signup.html.erb
<h1>Staticpages#signup</h1>
<p>Find me in app/views/staticpages/signup.html.erb</p>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<h1>Listing users</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= user.email %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<% provide(:title,"Sign up") %>
<h1>Sign up</h1>

<div class="row">
	<div class="span6 offset3">
		<%= form_for(@user) do |f| %>
		
		<%=f.label :name %>
		<%= f.text_field :name %>

		<%=f.label :email %>
		<%= f.text_field :email %>

		<%=f.label :password %>
		<%= f.password_field :password %>

		<%=f.label :password_confirmation,"Confirmation" %>
		<%= f.password_field :password_confirmation %>

	<%= f.submit "Create my account",class: "btn btn-large btn-primary" %>
	<%end%>
   </div>
</div>

app/views/users/show.html.erb
<% provide(:title,@user.name) %>
	<h1><%= @user.name%></h1>

<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @user.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>